# Generated by Django 4.2.2 on 2023-08-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availablevaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Healthcentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_name', models.CharField(max_length=30)),
                ('health_address', models.TextField()),
                ('health_phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('health_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_name', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('no_wards', models.CharField(max_length=30)),
                ('no_mens', models.CharField(max_length=30)),
                ('no_womens', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=30)),
                ('scheme_desc', models.TextField()),
                ('scheme_eligibility', models.TextField()),
                ('scheme_procedure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=30)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.panchayat')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.ward')),
                ('worker_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=30)),
                ('vaccination_desc', models.TextField()),
                ('vaccination_age', models.CharField(max_length=30)),
                ('disease_prevented', models.CharField(max_length=30)),
                ('dose', models.CharField(max_length=30)),
                ('healthcentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.healthcentre')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_date', models.DateField()),
                ('vaccination_from', models.TimeField()),
                ('vaccination_to', models.TimeField()),
                ('availablevaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.availablevaccination')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_name', models.CharField(max_length=30)),
                ('tip_desc', models.TextField()),
                ('tip_image', models.ImageField(blank=True, upload_to='')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('is_child', models.BooleanField(blank=True)),
                ('is_pregnant', models.BooleanField(blank=True)),
                ('pregnancy_month', models.CharField(max_length=30)),
                ('mother_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.worker')),
            ],
        ),
        migrations.AddField(
            model_name='healthcentre',
            name='panchayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.panchayat'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_on', models.DateField(auto_now_add=True)),
                ('food_list', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=30)),
                ('disease_image', models.ImageField(blank=True, upload_to='')),
                ('disease_desc', models.TextField()),
                ('disease_symptoms', models.TextField()),
                ('disease_prevention', models.TextField()),
                ('healthcentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.healthcentre')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.mother')),
            ],
        ),
        migrations.AddField(
            model_name='availablevaccination',
            name='healthcentre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.healthcentre'),
        ),
        migrations.AddField(
            model_name='availablevaccination',
            name='vaccinationInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare_app.vaccinationinfo'),
        ),
    ]
