# Generated by Django 4.2.2 on 2023-08-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0003_worker_panchayat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panchayat',
            name='no_mens',
        ),
        migrations.RemoveField(
            model_name='panchayat',
            name='no_wards',
        ),
        migrations.RemoveField(
            model_name='panchayat',
            name='no_womens',
        ),
        migrations.AddField(
            model_name='panchayat',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='panchayat_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='panchayat',
            name='pin',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
