# Generated by Django 4.2.2 on 2023-08-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0004_remove_panchayat_no_mens_remove_panchayat_no_wards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='pregnancy_month',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
