# Generated by Django 4.2.2 on 2023-08-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0005_alter_mother_pregnancy_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='weight',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='pregnancy_weight',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
