# Generated by Django 4.2.2 on 2023-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0006_child_weight_mother_pregnancy_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='is_pregnant',
            field=models.BooleanField(blank=True, default='no'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pregnancy_month',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pregnancy_weight',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
