# Generated by Django 4.2.2 on 2023-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0007_alter_mother_is_pregnant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='is_child',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='is_pregnant',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
    ]
