# Generated by Django 4.2.2 on 2023-08-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0008_alter_mother_is_child_alter_mother_is_pregnant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='tip_image',
        ),
    ]
