# Generated by Django 4.2.2 on 2023-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0009_remove_tips_tip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='detail_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_for',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
