# Generated by Django 4.2.2 on 2023-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0011_scheme_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='disease_image',
        ),
        migrations.AddField(
            model_name='disease',
            name='published_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
