# Generated by Django 4.2.2 on 2023-08-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0012_remove_disease_disease_image_disease_published_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='disease_name',
            new_name='disease_title',
        ),
    ]
