# Generated by Django 4.2.2 on 2023-08-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0013_rename_disease_name_disease_disease_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationdate',
            name='availablevaccination',
        ),
        migrations.AddField(
            model_name='vaccinationdate',
            name='vaccinationinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babycare_app.vaccinationinfo'),
        ),
        migrations.AddField(
            model_name='vaccinationinfo',
            name='availabecount',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Availablevaccination',
        ),
    ]
