# Generated by Django 4.2.2 on 2023-08-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0014_remove_vaccinationdate_availablevaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationinfo',
            name='published_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
