# Generated by Django 4.2.2 on 2023-08-09 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0015_vaccinationinfo_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdate',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babycare_app.worker'),
        ),
    ]
