# Generated by Django 4.2.2 on 2023-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0016_vaccinationdate_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='pregnancy_month',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pregnancy_weight',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
