# Generated by Django 4.2.2 on 2023-08-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0019_remove_food_mother_remove_worker_panchayat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationinfo',
            name='worker',
        ),
    ]
