# Generated by Django 4.2.2 on 2023-08-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0020_remove_vaccinationinfo_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='panchayat',
            name='wardno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
