# Generated by Django 4.2.2 on 2023-08-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare_app', '0023_alter_worker_ward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
